[versions]
junit-jupiter = "5.11.3"
wiremock = "3.12.1"
logback = "1.5.6"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
